const medusasAsset = (filename) => new URL(`../assets/images/projects/illustrations/medusas/${filename}`, import.meta.url).href
const donutsAsset = (filename) => new URL(`../assets/images/projects/3d/3d-donuts/${filename}`, import.meta.url).href
const deepSeaAsset = (filename) => new URL(`../assets/images/projects/illustrations/deep-sea/${filename}`, import.meta.url).href
const forestAsset = (filename) => new URL(`../assets/images/projects/illustrations/forest/${filename}`, import.meta.url).href
const muchomixBiomesAsset = (filename) => new URL(`../assets/images/projects/illustrations/biomas/${filename}`, import.meta.url).href
const jungleAsset = (filename) => new URL(`../assets/images/projects/illustrations/jungle/${filename}`, import.meta.url).href
const gameIconsAsset = (filename) => new URL(`../assets/images/projects/illustrations/game-icons/${filename}`, import.meta.url).href
const reindeerAsset = (filename) => new URL(`../assets/images/projects/illustrations/reindeer/${filename}`, import.meta.url).href
const snapchatFramesAsset = (filename) => new URL(`../assets/images/projects/illustrations/snapchat-frames/${filename}`, import.meta.url).href
const muchokidsNationalitiesAsset = (filename) => new URL(`../assets/images/projects/illustrations/muchokids-nationalities/${filename}`, import.meta.url).href
const muranaAsset = (filename) => new URL(`../assets/images/projects/front-end-ux/murana/${filename}`, import.meta.url).href
const donutShopAsset = (filename) => new URL(`../assets/images/projects/front-end-ux/donut-shop/${filename}`, import.meta.url).href
const candlesAssets = {
  hero: new URL('../assets/images/projects/illustrations/candles/velas.png', import.meta.url).href,
  guidelines: new URL('../assets/images/projects/illustrations/candles/logo-angel.jpg', import.meta.url).href,
  logo: new URL('../assets/images/projects/illustrations/candles/logo-cuadrado.jpg', import.meta.url).href,
  label: new URL('../assets/images/projects/illustrations/candles/label.svg', import.meta.url).href,
  dogsApplication: new URL('../assets/images/projects/illustrations/candles/vela-dogs.png', import.meta.url).href,
  sacredFireApplication: new URL('../assets/images/projects/illustrations/candles/vela-dragon.png', import.meta.url).href,
  enchantedBlossomApplication: new URL('../assets/images/projects/illustrations/candles/vela-enchanted.png', import.meta.url).href,
  mountainPine: new URL('../assets/images/projects/illustrations/candles/MountainPine-22-5x22-5.png', import.meta.url).href,
  auroraDawn: new URL('../assets/images/projects/illustrations/candles/aurora-dawn-25x25-centered.png', import.meta.url).href,
  cherryBlossom: new URL('../assets/images/projects/illustrations/candles/cherry-blossom-25x25-center.png', import.meta.url).href,
  christmasElements: new URL('../assets/images/projects/illustrations/candles/christmas-elements.png', import.meta.url).href,
  enchantedBlossom: new URL('../assets/images/projects/illustrations/candles/enchanted-blossom-25x25-center.png', import.meta.url).href,
  lavender: new URL('../assets/images/projects/illustrations/candles/lavender-25x25-center.png', import.meta.url).href,
  mahogany: new URL('../assets/images/projects/illustrations/candles/mahogany-candle-illustration-entregable.png', import.meta.url).href,
  sacredFire: new URL('../assets/images/projects/illustrations/candles/sacred-fire-25x25-center.png', import.meta.url).href,
  santaAndGifts: new URL('../assets/images/projects/illustrations/candles/santa-and-gifts-25x25-white-smaller.png', import.meta.url).href,
  tenDogs: new URL('../assets/images/projects/illustrations/candles/ten-dogs-smaller.png', import.meta.url).href,
  lavenderProcess: new URL('../assets/images/projects/illustrations/candles/lavender-process-web.m4v', import.meta.url).href,
  sacredFireProcess: new URL('../assets/images/projects/illustrations/candles/sacred-fire-process-web.m4v', import.meta.url).href,
}
const muchomixGameAssets = {
  gameplay: new URL('../assets/images/projects/illustrations/muchomix-game/gameplay.jpg', import.meta.url).href,
  goodJob: new URL('../assets/images/projects/illustrations/muchomix-game/good-job-screen.jpg', import.meta.url).href,
  howToPlay: new URL('../assets/images/projects/illustrations/muchomix-game/how-to-play.jpg', import.meta.url).href,
  villainWarning: new URL('../assets/images/projects/illustrations/muchomix-game/howto.jpg', import.meta.url).href,
  levels: new URL('../assets/images/projects/illustrations/muchomix-game/levels.jpg', import.meta.url).href,
  powerStones: new URL('../assets/images/projects/illustrations/muchomix-game/power-stones.jpg', import.meta.url).href,
  ranking: new URL('../assets/images/projects/illustrations/muchomix-game/ranking.jpg', import.meta.url).href,
  timesUp: new URL('../assets/images/projects/illustrations/muchomix-game/timesup.jpg', import.meta.url).href,
  friends: new URL('../assets/images/projects/illustrations/muchomix-game/friends.jpg', import.meta.url).href,
  yourFriends: new URL('../assets/images/projects/illustrations/muchomix-game/your-friends.jpg', import.meta.url).href,
}
const organicShapeAsset = (filename) => new URL(`../assets/images/shapes/organic/${filename}`, import.meta.url).href
const arrowShapeAsset = (filename) => new URL(`../assets/images/shapes/flechas/${filename}`, import.meta.url).href
const processArrowAsset = (filename, mobileRotation, desktopRotation) => ({
  src: arrowShapeAsset(filename),
  mobileRotation,
  desktopRotation,
})

export const projectDetails = {
  'who-is-paying': {
    layout: 'who-is-paying',
    palette: ['#D9CDD7', '#8F4282', '#5D495A', '#D9B5AE', '#FFFFFF'],
    links: [
      { id: 'repository', href: 'https://github.com/vanessadugarte/who-is-paying' },
    ],
  },
  'donut-shop': {
    heroImage: donutShopAsset('chocolate.png'),
    heroDimensions: { width: 700, height: 700 },
    palette: ['#FDF3F5', '#E70D0D', '#FF66A6', '#FFFFFF'],
    detailImages: [
      donutShopAsset('chocolate.png'),
      donutShopAsset('arequipe.png'),
      donutShopAsset('fresa.png'),
      donutShopAsset('cookies-and-cream.png'),
    ],
    detailImageDimensions: Array.from({ length: 4 }, () => ({ width: 700, height: 700 })),
    links: [
      { id: 'demo', href: 'https://vanessadugarte.github.io/carrito-donas-coderhouse/' },
      { id: 'repository', href: 'https://github.com/vanessadugarte/carrito-donas-coderhouse' },
    ],
  },
  murana: {
    layout: 'murana',
    heroImage: muranaAsset('hero.webp'),
    heroDimensions: { width: 2077, height: 734 },
    categories: [
      { id: 'shampoo', image: muranaAsset('category-shampoo.webp') },
      { id: 'bodyGel', image: muranaAsset('category-body-gel.webp') },
      { id: 'hairMasks', image: muranaAsset('category-hair-masks.webp') },
      { id: 'facialCleansers', image: muranaAsset('category-facial-cleansers.webp') },
      { id: 'skinCare', image: muranaAsset('category-skin-care.webp') },
      { id: 'giftSets', image: muranaAsset('category-gift-sets.webp') },
    ],
    carePillars: [
      { id: 'hair', image: muranaAsset('hair-care.webp') },
      { id: 'face', image: muranaAsset('facial-care.webp') },
      { id: 'body', image: muranaAsset('body-care.webp') },
    ],
    lookbook: [
      { id: 'facial', image: muranaAsset('lookbook-facial.webp'), width: 944, height: 1140 },
      { id: 'products', image: muranaAsset('lookbook-products.webp'), width: 588, height: 710 },
      { id: 'body', image: muranaAsset('lookbook-body-care.webp'), width: 944, height: 1140 },
      { id: 'lemon', image: muranaAsset('lookbook-lemon.webp'), width: 944, height: 1140 },
      { id: 'lotion', image: muranaAsset('lookbook-body-lotion.webp'), width: 588, height: 710 },
      { id: 'hair', image: muranaAsset('lookbook-hair-care.webp'), width: 944, height: 1140 },
      { id: 'hairProducts', image: muranaAsset('lookbook-hair-products.webp'), width: 454, height: 548 },
      { id: 'hairModel', image: muranaAsset('lookbook-hair-model.webp'), width: 454, height: 548 },
    ],
    products: [
      { id: 'argan', image: muranaAsset('product-argan.webp') },
      { id: 'antiage', image: muranaAsset('product-antiage.webp') },
      { id: 'hydration', image: muranaAsset('product-hydration.webp') },
      { id: 'dailyCleanse', image: muranaAsset('product-daily-cleanse.webp') },
    ],
  },
  medusas: {
    heroImage: medusasAsset('finalwork-medusas.jpg'),
    illustrationTreatment: true,
    accentColor: '#004461',
    organicMasks: {
      hero: organicShapeAsset('organic-shape-horiz.svg'),
      details: [
        organicShapeAsset('organic-shape-05.svg'),
        organicShapeAsset('organic-shape-02.svg'),
        organicShapeAsset('organic-shape-03.svg'),
        organicShapeAsset('organic-shape-04.svg'),
      ],
    },
    decorationImage: medusasAsset('sample.png'),
    referenceImages: [medusasAsset('inspo-1.jpg'), medusasAsset('inspo-2.jpg')],
    processImages: [
      medusasAsset('sketch-1-medusas.jpg'),
      medusasAsset('sketch-2-medusas.jpg'),
      medusasAsset('sketch-3-medusas.jpg'),
      medusasAsset('sketch-4-medusas.jpg'),
    ],
    processArrows: [
      processArrowAsset('flecha-01.svg', 90, 0),
      processArrowAsset('flecha-06.svg', 90, 0),
      processArrowAsset('flecha-09.svg', 180, 90),
    ],
    detailImages: [
      medusasAsset('detail-1-medusas.png'),
      medusasAsset('detail-2-medusas.jpg'),
      medusasAsset('detail-3-medusas.jpg'),
      medusasAsset('detail-4-medusas.jpg'),
    ],
    palette: ['#001b2a', '#004461', '#087fac', '#09c0e8', '#05a64e', '#4df024'],
  },
  'donas-3d': {
    heroImage: donutsAsset('final-donuts3d.jpg'),
    palette: ['#F5C6D8', '#E96486', '#F4B35E', '#B6E2C4', '#8E5A3C', '#E8D6C2'],
    processImages: [
      donutsAsset('sketch-1-donuts.jpg'),
      donutsAsset('sketch-2-donuts.jpg'),
      donutsAsset('sketch-3-donuts.jpg'),
      donutsAsset('sketch-4-donuts.jpg'),
    ],
    processWideImages: [
      donutsAsset('modelado-1.jpg'),
      donutsAsset('modelado-2.jpg'),
    ],
    detailImages: [
      donutsAsset('detail-donut-1.jpg'),
      donutsAsset('detail-donut-2.jpg'),
      donutsAsset('detail-donut-3.jpg'),
      donutsAsset('detail-donut-4.jpg'),
    ],
  },
  'deep-sea': {
    heroImage: deepSeaAsset('finalwork-deepsea.jpg'),
    heroDimensions: { width: 1200, height: 891 },
    illustrationTreatment: true,
    accentColor: '#041A3D',
    heroSecondaryImage: deepSeaAsset('complete-work-deepsea.jpg'),
    heroSecondaryDimensions: { width: 1200, height: 1618 },
    decorationImage: deepSeaAsset('adorno-deepsea.png'),
    heroDecorations: [
      deepSeaAsset('little-fish-1.svg'),
      deepSeaAsset('little-fish-2.svg'),
      deepSeaAsset('little-fish-3.svg'),
      deepSeaAsset('adorno-fish.svg'),
    ],
    heroReferenceImages: [deepSeaAsset('inspo-1.jpg'), deepSeaAsset('inspo-2.jpg')],
    heroReferenceImageDimensions: Array.from({ length: 2 }, () => ({ width: 760, height: 500 })),
    organicMasks: {
      hero: organicShapeAsset('organic-shape-02.svg'),
      heroSecondary: organicShapeAsset('organic-shape-05.svg'),
      details: [
        organicShapeAsset('organic-shape-01.svg'),
        organicShapeAsset('organic-shape-05.svg'),
        organicShapeAsset('organic-shape-04.svg'),
        organicShapeAsset('organic-shape-03.svg'),
      ],
    },
    palette: ['#041A3D', '#0A2836', '#23384D', '#578288', '#94CCD1', '#593D58', '#C098C2'],
    palettePlacement: 'hero',
    processImages: [
      deepSeaAsset('sketch-0-deep-sea.jpg'),
      deepSeaAsset('sketch-deepsea-1.jpg'),
      deepSeaAsset('sketch-deepsea-2.jpg'),
      deepSeaAsset('sketch-deepsea-3.png'),
    ],
    processImageDimensions: [
      { width: 760, height: 500 },
      { width: 760, height: 500 },
      { width: 760, height: 500 },
      { width: 760, height: 500 },
    ],
    processArrows: [
      processArrowAsset('flecha-02.svg', 180, 90),
      processArrowAsset('flecha-07.svg', 0, -90),
      processArrowAsset('flecha-04.svg', 0, -90),
    ],
    detailImages: [
      deepSeaAsset('detail-deepsea-1.jpg'),
      deepSeaAsset('detail-deepsea-2.jpg'),
      deepSeaAsset('detail-deepsea-3.jpg'),
      deepSeaAsset('detail-deepsea-4.jpg'),
    ],
  },
  forest: {
    heroImage: forestAsset('forest-finalwork.jpg'),
    heroDimensions: { width: 1920, height: 2561 },
    illustrationTreatment: true,
    accentColor: '#0C2C31',
    palette: ['#061314', '#0C2C31', '#24555B', '#5EB5C0', '#16451F', '#559B39'],
    processImages: [
      forestAsset('forest-process-1.png'),
      forestAsset('forest-process-2.jpg'),
      forestAsset('forest-process-3.jpg'),
    ],
    processImageDimensions: [
      { width: 2048, height: 2732 },
      { width: 1920, height: 2561 },
      { width: 1920, height: 2561 },
    ],
    processArrows: [
      processArrowAsset('flecha-01.svg', 90, 0),
      processArrowAsset('flecha-06.svg', 90, 0),
    ],
  },
  'muchomix-biomas': {
    layout: 'biomes',
    accentColor: '#075B78',
    secondaryAccentColor: '#D95622',
    biomes: [
      { id: 'ice-zone', image: muchomixBiomesAsset('ice zone.jpg'), width: 2048, height: 2732 },
      { id: 'snow-mountains', image: muchomixBiomesAsset('snow mountains.jpg'), width: 2048, height: 2732 },
      { id: 'mountains', image: muchomixBiomesAsset('mountains.jpg'), width: 2048, height: 2732 },
      { id: 'flower-field', image: muchomixBiomesAsset('flower field.jpg'), width: 2048, height: 2732 },
      { id: 'beach', image: muchomixBiomesAsset('beach.jpg'), width: 2048, height: 2732 },
      { id: 'cactus-desert', image: muchomixBiomesAsset('cactus desert.jpg'), width: 2048, height: 2732 },
      { id: 'desert-dunes', image: muchomixBiomesAsset('dunes desert.jpg'), width: 2048, height: 2732 },
      { id: 'space', image: muchomixBiomesAsset('space.jpg'), width: 2048, height: 2732 },
    ],
  },
  jungle: {
    heroImage: jungleAsset('jungle-illustration-complete.jpg'),
    heroDimensions: { width: 1200, height: 1490 },
    illustrationTreatment: true,
    accentColor: '#6B8534',
    heroDecorations: [
      jungleAsset('adorno-jungle-01.svg'),
      jungleAsset('adorno-jungle-02.svg'),
      jungleAsset('adorno-jungle-03.svg'),
    ],
    heroReferenceImages: [
      jungleAsset('swamp-reference.jpg'),
      jungleAsset('swamp-reference-2.jpg'),
    ],
    heroReferenceImageDimensions: Array.from({ length: 2 }, () => ({ width: 576, height: 842 })),
    organicMasks: {
      hero: organicShapeAsset('organic-shape-02.svg'),
      details: [
        organicShapeAsset('organic-shape-05.svg'),
        organicShapeAsset('organic-shape-02.svg'),
        organicShapeAsset('organic-shape-03.svg'),
        organicShapeAsset('organic-shape-04.svg'),
        organicShapeAsset('organic-shape-01.svg'),
      ],
    },
    processArrows: [
      processArrowAsset('flecha-05.svg', 0, -90),
      processArrowAsset('flecha-08.svg', -45, -135),
      processArrowAsset('flecha-04.svg', 0, -90),
    ],
    palette: ['#332B1D', '#51472D', '#B9AE92', '#A29D2A', '#EAE62B', '#C53F18', '#3F5B2B', '#6B8534'],
    palettePlacement: 'hero',
    processImages: [
      jungleAsset('jungle-sketch12026.jpg'),
      jungleAsset('jungle-sketch22026.jpg'),
      jungleAsset('jungle-sketch32026.jpg'),
      jungleAsset('swamp process.jpg'),
    ],
    processImageDimensions: [
      { width: 655, height: 842 },
      { width: 655, height: 842 },
      { width: 655, height: 842 },
      { width: 2048, height: 2732 },
    ],
    detailImages: [
      jungleAsset('jungle-detail1.jpg'),
      jungleAsset('jungle-detail2.jpg'),
      jungleAsset('jungle-detail3.jpg'),
      jungleAsset('jungle-detail4.jpg'),
      jungleAsset('jungle-detail5.jpg'),
    ],
    detailImageDimensions: Array.from({ length: 5 }, () => ({ width: 706, height: 500 })),
  },
  'game-icons': {
    heroImage: gameIconsAsset('game-icons-complete.jpg'),
    heroDimensions: { width: 1200, height: 1192 },
    heroSecondaryImage: gameIconsAsset('icons-objects.jpg'),
    heroSecondaryDimensions: { width: 2048, height: 2732 },
    illustrationTreatment: true,
    accentColor: '#E90051',
    decorationImage: gameIconsAsset('adorno-icons.svg'),
    palette: ['#04031F', '#590023', '#E90051', '#FF5B99', '#2BBFAF', '#F8B900'],
    palettePlacement: 'process',
    processImages: [
      gameIconsAsset('game-icons-process-1.jpg'),
      gameIconsAsset('game-icons-process-3.jpg'),
      gameIconsAsset('game-icons-process-2.jpg'),
    ],
    processImageDimensions: [
      { width: 673, height: 542 },
      { width: 1398, height: 1125 },
      { width: 673, height: 542 },
    ],
    processArrows: [
      processArrowAsset('flecha-01.svg', 90, 0),
      processArrowAsset('flecha-06.svg', 90, 0),
    ],
    detailImages: [
      gameIconsAsset('icons-detail-2.png'),
      gameIconsAsset('coins-02.svg'),
      gameIconsAsset('coins-03.svg'),
      gameIconsAsset('coins-04.svg'),
      gameIconsAsset('coins-05.svg'),
      gameIconsAsset('coins-06.svg'),
      gameIconsAsset('coins-07.svg'),
      gameIconsAsset('estrella-candado.png'),
      gameIconsAsset('icons-detail-4.png'),
    ],
    detailImageDimensions: [
      { width: 617, height: 500 },
      { width: 177, height: 167 },
      { width: 177, height: 167 },
      { width: 177, height: 167 },
      { width: 177, height: 167 },
      { width: 177, height: 167 },
      { width: 177, height: 167 },
      { width: 1230, height: 1278 },
      { width: 1136, height: 1816 },
    ],
  },
  reindeer: {
    heroImage: reindeerAsset('complete-illustration.jpg'),
    heroDimensions: { width: 1000, height: 798 },
    illustrationTreatment: true,
    accentColor: '#4F5D4B',
    palette: ['#4F5D4B', '#D4BB9B', '#E8E9D8', '#EBC4CE', '#BDAF91', '#E98D74'],
    processImages: [
      reindeerAsset('deer-process-1.png'),
      reindeerAsset('deer-process-2.jpg'),
      reindeerAsset('deer-process3.jpg'),
    ],
    processImageDimensions: [
      { width: 1269, height: 1240 },
      { width: 3258, height: 3225 },
      { width: 698, height: 693 },
    ],
    processArrows: [
      processArrowAsset('flecha-01.svg', 90, 0),
      processArrowAsset('flecha-06.svg', 90, 0),
    ],
    detailImages: [reindeerAsset('complete-illustration-2.png')],
    detailImageDimensions: [{ width: 1536, height: 1024 }],
    closeupImages: [
      reindeerAsset('reindeer-detail1.jpg'),
      reindeerAsset('reindeer-detail2.jpg'),
      reindeerAsset('reindeer-detail3.jpg'),
      reindeerAsset('reindeer-detail4.jpg'),
    ],
  },
  'snapchat-frames': {
    layout: 'gallery',
    accentColor: '#E90051',
    secondaryAccentColor: '#008F87',
    isolatedAssets: [
      { image: snapchatFramesAsset('snapchat-assets-01.svg'), width: 67, height: 251 },
      { image: snapchatFramesAsset('snapchat-assets-02.svg'), width: 229, height: 197 },
      { image: snapchatFramesAsset('snapchat-assets-03.svg'), width: 209, height: 125 },
      { image: snapchatFramesAsset('snapchat-assets-04.svg'), width: 168, height: 149 },
      { image: snapchatFramesAsset('snapchat-assets-05.svg'), width: 174, height: 77 },
      { image: snapchatFramesAsset('snapchat-assets-06.svg'), width: 157, height: 139 },
      { image: snapchatFramesAsset('snapchat-assets-07.svg'), width: 58, height: 89 },
      { image: snapchatFramesAsset('snapchat-assets-08.svg'), width: 52, height: 60 },
      { image: snapchatFramesAsset('snapchat-assets-09.svg'), width: 231, height: 184 },
      { image: snapchatFramesAsset('snapchat-assets-10.svg'), width: 129, height: 153 },
      { image: snapchatFramesAsset('snapchat-assets-11.svg'), width: 123, height: 227 },
      { image: snapchatFramesAsset('snapchat-assets-13.svg'), width: 131, height: 316 },
      { image: snapchatFramesAsset('snapchat-assets-14.svg'), width: 145, height: 242 },
    ],
    frames: [
      { id: 'china', image: snapchatFramesAsset('China-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'egypt', image: snapchatFramesAsset('egypt-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'india', image: snapchatFramesAsset('india-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'mexico', image: snapchatFramesAsset('Mexico-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'france', image: snapchatFramesAsset('france-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'italy', image: snapchatFramesAsset('italy-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'england', image: snapchatFramesAsset('england-verticalframe.jpg'), width: 2048, height: 2732 },
      { id: 'ireland', image: snapchatFramesAsset('Ireland-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'spain', image: snapchatFramesAsset('spain-vertical.jpg'), width: 8533, height: 11383 },
      { id: 'cuba', image: snapchatFramesAsset('cuba-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'netherlands', image: snapchatFramesAsset('Holanda-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'russia', image: snapchatFramesAsset('russia-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'united-states', image: snapchatFramesAsset('United-states-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'germany', image: snapchatFramesAsset('Germany-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'sweden', image: snapchatFramesAsset('Sweden-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'south-korea', image: snapchatFramesAsset('Korea-vertical.jpg'), width: 2048, height: 2732 },
      { id: 'arab', image: snapchatFramesAsset('arab-vertical.jpg'), width: 4267, height: 5692 },
      { id: 'muchokids', image: snapchatFramesAsset('muchokids-vertical.jpg'), width: 2048, height: 2732 },
    ],
  },
  'muchokids-nationalities': {
    layout: 'nationalities',
    heroImage: muchokidsNationalitiesAsset('nacionalidadesmapa-12.svg'),
    heroDimensions: { width: 1390, height: 1553 },
    backgroundImage: muchokidsNationalitiesAsset('fondo-brasil.png'),
    backgroundDimensions: { width: 1200, height: 536 },
    flagImage: muchokidsNationalitiesAsset('brazil-10.svg'),
    characters: [
      { id: 'spain', image: muchokidsNationalitiesAsset('nacionalidad-frame-01.svg') },
      { id: 'united-states', image: muchokidsNationalitiesAsset('nacionalidad-frame-02.svg') },
      { id: 'netherlands', image: muchokidsNationalitiesAsset('nacionalidad-frame-03.svg') },
      { id: 'norway', image: muchokidsNationalitiesAsset('nacionalidad-frame-04.svg') },
      { id: 'mexico', image: muchokidsNationalitiesAsset('nacionalidad-frame-06.svg') },
      { id: 'kenya', image: muchokidsNationalitiesAsset('nacionalidad-frame-07.svg') },
      { id: 'cuba', image: muchokidsNationalitiesAsset('nacionalidad-frame-08.svg') },
      { id: 'australia', image: muchokidsNationalitiesAsset('nacionalidad-frame-11.svg') },
      { id: 'japan', image: muchokidsNationalitiesAsset('nacionalidad-frame-14.svg') },
      { id: 'france', image: muchokidsNationalitiesAsset('nacionalidad-frame-15.svg') },
      { id: 'india', image: muchokidsNationalitiesAsset('nacionalidad-frame-18.svg') },
      { id: 'united-arab-emirates', image: muchokidsNationalitiesAsset('nacionalidad-frame-19.svg') },
      { id: 'netherlands-cap', image: muchokidsNationalitiesAsset('nacionalidad-frame-20.svg') },
      { id: 'united-kingdom', image: muchokidsNationalitiesAsset('nacionalidad-frame-21.svg') },
      { id: 'canada', image: muchokidsNationalitiesAsset('nacionalidad-frame-22.svg') },
    ],
  },
  'muchomix-game': {
    layout: 'game',
    accentColor: '#E90051',
    secondaryAccentColor: '#008F87',
    heroImage: muchomixGameAssets.gameplay,
    heroDimensions: { width: 1920, height: 2561 },
    sections: [
      {
        id: 'gameplay',
        screens: [
          { id: 'how-to-play', image: muchomixGameAssets.howToPlay, width: 1920, height: 2561 },
          { id: 'villain-warning', image: muchomixGameAssets.villainWarning, width: 750, height: 1334 },
        ],
      },
      {
        id: 'progression',
        screens: [
          { id: 'levels', image: muchomixGameAssets.levels, width: 1920, height: 2561 },
          { id: 'power-stones', image: muchomixGameAssets.powerStones, width: 1920, height: 2561 },
        ],
      },
      {
        id: 'results',
        screens: [
          { id: 'good-job', image: muchomixGameAssets.goodJob, width: 1920, height: 2561 },
          { id: 'times-up', image: muchomixGameAssets.timesUp, width: 2048, height: 2732 },
          { id: 'ranking', image: muchomixGameAssets.ranking, width: 750, height: 1334 },
        ],
      },
      {
        id: 'social',
        screens: [
          { id: 'friends', image: muchomixGameAssets.friends, width: 1920, height: 2561 },
          { id: 'your-friends', image: muchomixGameAssets.yourFriends, width: 1920, height: 2561 },
        ],
      },
    ],
  },
  'angels-sighs': {
    layout: 'candles',
    accentColor: '#4F3617',
    secondaryAccentColor: '#A45764',
    heroImage: candlesAssets.hero,
    heroDimensions: { width: 1404, height: 1120 },
    brand: {
      guidelinesImage: candlesAssets.guidelines,
      guidelinesDimensions: { width: 1366, height: 1141 },
      logoImage: candlesAssets.logo,
      logoDimensions: { width: 567, height: 567 },
      labelImage: candlesAssets.label,
      labelDimensions: { width: 239, height: 224 },
    },
    applications: [
      { id: 'dogs', image: candlesAssets.dogsApplication, width: 1086, height: 1448 },
      { id: 'sacred-fire', image: candlesAssets.sacredFireApplication, width: 1465, height: 1074 },
      { id: 'enchanted-blossom', image: candlesAssets.enchantedBlossomApplication, width: 1212, height: 1298 },
    ],
    illustrations: [
      { id: 'mountain-pine', image: candlesAssets.mountainPine },
      { id: 'aurora-dawn', image: candlesAssets.auroraDawn },
      { id: 'cherry-blossom', image: candlesAssets.cherryBlossom },
      { id: 'christmas-elements', image: candlesAssets.christmasElements },
      { id: 'enchanted-blossom', image: candlesAssets.enchantedBlossom },
      { id: 'lavender', image: candlesAssets.lavender },
      { id: 'mahogany', image: candlesAssets.mahogany },
      { id: 'sacred-fire', image: candlesAssets.sacredFire },
      { id: 'santa-and-gifts', image: candlesAssets.santaAndGifts },
      { id: 'ten-dogs', image: candlesAssets.tenDogs },
    ],
    processVideos: [
      {
        id: 'lavender',
        src: candlesAssets.lavenderProcess,
        poster: candlesAssets.lavender,
      },
      {
        id: 'sacred-fire',
        src: candlesAssets.sacredFireProcess,
        poster: candlesAssets.sacredFire,
      },
    ],
  },
}

export function getProjectDetails(projectId) {
  return projectDetails[projectId]
}
